name: 小狗帽子和永恒泡芙
description: |
  一些我存在的证据，在时光里它们曾部分代表或属于我。

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page:num/'
  title_suffix: ' - 第 :num 页'
  index_page_name: 'index.html'

sass:
  style: :compressed

navigation:
  - { name: "气球悲歌", url: "/category/balloon/" }
  - { name: "蓝色干燥剂之死", url: "/category/desiccant/" }
  - { name: "琐", url: "/category/something/" }
  - { name: "照片", url: "/category/photos/" }
  - { name: "关于我", url: "/about" }

footer-links:
  instagram: darkclouds_watch 

exclude: [Gemfile, Gemfile.lock, node_modules, vendor, .listen_test, .github]
